[FOLDER TO ANALYZE]
folder = similarity_csv

[CSV TO ANALYZE]
file = antipasti.csv

[COOKBOOK FOLDER TO ANALYZE]
folder = cartella_portate

[JSON COOKBOOK TO ANALYZE]
file = Cookbook_SingleServing.json

[RECIPE TO ANALYZE]
recipe = alici gratinate al forno
