[FOLDER TO ANALYZE]
folder = cartella_portate

[JSON TO ANALYZE]
file1 = antipasti.json
file2 = primi-piatti.json
file3 = secondi-piatti.json
file4 = contorni.json
file5 = dolci.json
file6 = lievitati.json
file7 = piatti-unici.json
file8 = salse-e-sughi.json
file9 = conserve.json
file10 = zuppe-e-minestre.json
file11 = ricette-di-base.json
file12 = bevande.json

[COOKBOOK FOLDER TO ANALYZE]
folder = cartella_portate

[JSON COOKBOOK TO ANALYZE]
file = Cookbook_SingleServing.json

